### ISSUE TITLE
Reactively changing the input's value

### ISSUE THREAD

**Issue by coniel** [lukemadera/meteor-autoform-pikaday#1]
I'm using pikaday with FullCalendar so that when a user select a time slot on the calendar it opens up a form in which the pikaday fields are pre-populated with the selected start and end times. The problem is that pikaday doesn't pickup these changes so it displays an ugly string.

I could pikaday's setDate (and setMoment) function to update the value, but I'm not sure how to use it since I don't have access to the 'picker' object that it is created (or do I?).

Ideally, it be great if setDate/Moment was run automatically every time the input's value was reactively changed (if that's possible).

**Comment by lukemadera** [comment]
Sorry the slow reply. This module is basically deprecated in favor of https://github.com/notorii/meteor-autoform-datetimepicker - if you still have this issue there feel free to open a new issue and / or submit a pull request.
